### ISSUE TITLE
User Auth & Heroku

### ISSUE THREAD

**Issue by pfranciskoe** [pfranciskoe/CoffeeDTC#2]
https://dtcoffee.herokuapp.com/#/

- [x] Users can Log in
- [x] Users can Sign up
- [x] Errors occur when validations fail
- [x] Modal displays when it should
- [x] Current user status shows when logged in
- [x] Logout shows when logged in
- [x] Login shows when logged out

**Comment by Vanchen07** [comment]
Great job! I can sign up, login, and logout. Can you add a demo user functionality and let me know when that's done?

**Comment by pfranciskoe** [comment]
I want to add some fun css dynamic log in properties eventually but I have a solid working demo button for the meantime
