### ISSUE TITLE
Onboarding, Home Page, User-matches

### ISSUE THREAD

**Issue by pfranciskoe** [pfranciskoe/CoffeeDTC#3]
https://dtcoffee.herokuapp.com/#/

- [x] only logged-in users can access the on-boarding quiz.
- [x] users can select different options and submit their quiz results.
- [x]  the back end stores this 'taste profile' and creates appropriate coffee matches
- [x] once the user completes their quiz they are redirected to a page displaying their matches.
- [x] a logged in user that has already filled out the quiz can retake the quiz from the main page.
- [x] a logged in user can access their matched coffees from the nav bar or the main page.

**Comment by Vanchen07** [comment]
- I logged in but it doesn't indicate that I am until I click back to the main splash page
- Everything else looks really good and works as intended! Very nice!
