### ISSUE TITLE
CART, FOOTER DONE

### ISSUE THREAD

**Issue by pfranciskoe** [pfranciskoe/CoffeeDTC#4]
- [x] only logged in users can do the following.

- [x] add matched items to cart.

- [x] add additional duplicate items and see the total number of items added in the cart.

- [x] delete items from cart.

- [x] 'checkout cart' and see a message informing them that their order is en-route

- [x] if the cart is empty there will be an empty message

- [x] cart may be accessed from the sidebar, or the main splash page.

- [x] when items are added to the cart, buttons will turn green indicating a successful addition

**Comment by Vanchen07** [comment]
Looks great!
