### ISSUE TITLE
StoreFront, Search, Filters, Coffee Show Page

### ISSUE THREAD

**Issue by pfranciskoe** [pfranciskoe/CoffeeDTC#5]
## https://dtcoffee.herokuapp.com/#/
- Coffee storefront  
- [x] Users can view coffees in the store 
- [x] Users can sort and coffees based on various filters Logged in 
- [x] Filters update store contents instantly 
- [x] Users can search for coffees by name or roaster name
- [x] Search updates store contents instantly 
- Coffee details 
- [x] Users can view coffee details. 
- [x] Users can view associated roaster details. 
- [x] Users can add coffees to cart from this page.
- Google maps integration 
- [x] Users can see where the area coffee came from on a map
- [x] Users can see a pin at the roaster

**Comment by Vanchen07** [comment]
Awesome job on these features!
